### ISSUE TITLE
Tee Assembly fällt weg

### ISSUE THREAD

**Issue by photm5** [iblech/augsburger-linux-infotag#5]
Wie es aussieht, gibt es doch keine Tee Assembly:

> Date: Sat, 16 Apr 2016 04:48:58 +0200
> From: Richard Sailer <richard bei weltraumpflege.org>
> To: Diskussionen rund ums OpenLab <alle bei lists.openlab-augsburg.de>
> Subject: [openlab-alle] Doch keine Tee Assembly, weil Freiwilligenmangel
> 
> Hallo *,
> 
> Weil es uns morgen so wie es aussieht an freiwilligen mangelt.
> (Atm nur, profpatsch, julian, falk und ich, wobei keiner wirklich
> vollzeit) habe ich mich entschieden auf die Tee Assembly zu verzichten
> und stattdessen in dem Zeitraum am Openlab Stand zu sitzen.
> 
> Vlt. gibt es am Openlab Stand frisch gemahlenen Kaffee, weil ne Kaffee
> Maschine ist deutlich leichter zu "maintainen" als mehrere kannen
> japanische Tees.
> 
> Grüße
> -- Richi

**Comment by iblech** [comment]
On Fri, Apr 15, 2016 at 11:21:18PM -0700, shak-mar wrote:

> Wie es aussieht, gibt es doch keine Tee Assembly:

Danke! Und trotzdem ein großes Danke an @richi235 für die Bereitschaft
im Vorfeld, das zu organisieren. Auch, wenn es letztendlich nicht
geklappt hat, gab es ja trotzdem die Signalwirkung auf der Webseite.
Und die hat mir gut gefallen :-).
